//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Catalog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.Catalog.ProductResource", typeof(ProductResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The open-world action in Need for Speed Most Wanted gives you the freedom to drive your way. Hit jumps and shortcuts, switch cars, lie low, or head for terrain that plays to your vehicle’s unique strengths. Fight your way past cops and rivals using skill, high-end car tech, and tons of nitrous. It’s all about you, your friends, and a wild selection of cars. Let’s see what you can do..
        /// </summary>
        public static string Need_For_Speed_Most_Wanted___About {
            get {
                return ResourceManager.GetString("Need For Speed Most Wanted - About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCADXAcwDAREAAhEBAxEB/8QAHQAAAQQDAQEAAAAAAAAAAAAAAAUGBwgDBAkCAf/EAFEQAAEDAwMCBAMGAwUDCAUNAAECAwQFBhEAEiEHMQgTIkEUUWEJFSMycYFCUpEWJDNicheCoSU4Q1NzdbHBGDR0stEZJjU3Y3aDkpOztPDx/8QAHAEBAAIDAQEBAAAAAAAAAAAAAAMEAQIFBgcI/8QAQxEAAgECAwUFBwIEBQIFBQAAAAECAxEEITEFEkFRYQYTcYHwFCIykaGx0cHhBxVC8SMzUmJyFzQkNXOC [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Need_For_Speed_Most_Wanted___Image {
            get {
                return ResourceManager.GetString("Need For Speed Most Wanted - Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Redview County, where a street-racing rivalry between cops and racers never stops as both sides compete in an all-out war to take over the social, local, and national media..
        /// </summary>
        public static string Need_For_Speed_Rivals___About {
            get {
                return ResourceManager.GetString("Need For Speed Rivals - About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCADXAcwDAREAAhEBAxEB/8QAHQAAAQQDAQEAAAAAAAAAAAAABQMEBgcBAggACf/EAE4QAAEDAgQDBgMDCAcFBwQDAAECAwQFEQAGEiEHMUEIEyJRYXEUMoEjQpEVUmKhscHR8AkWJDNyguEXQ0RTYyWDkpWisvE0dJOjRVRz/8QAHAEAAwEBAQEBAQAAAAAAAAAAAAECAwQFBgcI/8QAQxEAAgECBAMFBQUFBgYDAQAAAAECAxEEEiExBUFRBhMiYXGBkaHR8BQyUrHBBxUjQuEWFyQzYpJDU3KCk/Fj [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Need_For_Speed_Rivals___Image {
            get {
                return ResourceManager.GetString("Need For Speed Rivals - Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race against time, outsmart the cops, and take on weekly qualifiers to reach The Grand, Lakeshore&apos;s ultimate street racing challenge. Pack your garage with precision-tuned, custom rides and light up the streets with your style, exclusive fits, and a vibrant global soundtrack that bumps in every corner of the world..
        /// </summary>
        public static string Need_For_Speed_Unbound___About {
            get {
                return ResourceManager.GetString("Need For Speed Unbound - About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCADXAcwDAREAAhEBAxEB/8QAHgAAAQUAAwEBAAAAAAAAAAAABgMEBQcIAAIJAQr/xABZEAACAQMCBAQDBQMHBgoHBgcBAgMEBREGEgAHITEIEyJBFFFhFTJCcYEjUpEJFjNiobHBFyRDcoLRJTRTc3WSorKz8BgZNTdjdOEmOFdkg9NUhZWWtLXx/8QAHQEAAAcBAQEAAAAAAAAAAAAAAAECAwQFBgcICf/EAEoRAAEDAgQDBAYIBAIJBAIDAAECAxEABAUSITEGQVETImFxBzKBkbHwFCMzQlKhwdEV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Need_For_Speed_Unbound___Image {
            get {
                return ResourceManager.GetString("Need For Speed Unbound - Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deadly virus engulfs the residents of Raccoon City in September of 1998, plunging the city into chaos as flesh eating zombies roam the streets for survivors. An unparalleled adrenaline rush, gripping storyline, and unimaginable horrors await you. Witness the return of Resident Evil 2..
        /// </summary>
        public static string Resident_Evil_2_Remake___About {
            get {
                return ResourceManager.GetString("Resident Evil 2 Remake - About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCADXAcwDAREAAhEBAxEB/8QAHgAAAAcBAQEBAAAAAAAAAAAAAAMEBQYHCAIBCQr/xABNEAABAwMDAgMFBQYDBQUFCQABAgMEAAURBhIhBzETQVEIFCJhcQkjMoGRFTNCobHBFiRSQ2LR4fAXGCU0giYoU3KyJzU2g4SSk9Lx/8QAHAEAAgMBAQEBAAAAAAAAAAAAAAIBAwQFBgcI/8QAQxEAAgEDAwIDBQQIBQIFBQAAAAECAxEhBBIxQVEFE2EicYGRoTKx0fAGFBUjQlLB4QczYnKyNfEWJDRTY0Nz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resident_Evil_2_Remake___Image {
            get {
                return ResourceManager.GetString("Resident Evil 2 Remake - Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jill Valentine is one of the last remaining people in Raccoon City to witness the atrocities Umbrella performed. To stop her, Umbrella unleashes their ultimate secret weapon: Nemesis! Also includes Resident Evil Resistance, a new 1 vs 4 online multiplayer game set in the Resident Evil universe..
        /// </summary>
        public static string Resident_Evil_3_Remake___About {
            get {
                return ResourceManager.GetString("Resident Evil 3 Remake - About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCADXAcwDAREAAhEBAxEB/8QAHgAAAAYDAQEAAAAAAAAAAAAAAAMEBQYHAQIICQr/xABNEAABAwMDAgMFBgIIAggDCQABAgMEAAURBhIhBzETQVEIFCJhcQkVMkKBkSOxFiQzUmKhwdFy4RdDRFOCkqLxGNLwGSU0RZSjsrPC/8QAHQEAAgMBAQEBAQAAAAAAAAAAAAIBAwQFBgcICf/EADkRAAICAQQBAgMFBwQCAgMAAAABAhEDBBIhMUETUQUiYQYUMnGBB0KRobHB8BUj0eE0UkNyM2KS/9oADAMB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resident_Evil_3_Remake___Image {
            get {
                return ResourceManager.GetString("Resident Evil 3 Remake - Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival is just the beginning. Six years have passed since the biological disaster in Raccoon City. Leon S. Kennedy, one of the survivors, tracks the president&apos;s kidnapped daughter to a secluded European village, where there is something terribly wrong with the locals..
        /// </summary>
        public static string Resident_Evil_4_Remake___About {
            get {
                return ResourceManager.GetString("Resident Evil 4 Remake - About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCADXAcwDAREAAhEBAxEB/8QAHgAAAQQDAQEBAAAAAAAAAAAABAIDBQYABwgBCQr/xABJEAACAQIEAwUFBgQEBAQFBQABAgMEEQAFEiEGMUEHEyJRYQgJMnGBFEKRobHwI1LB4RUW0fEkM2JyGCVDghc1U2OjRHSDouL/xAAcAQADAQEBAQEBAAAAAAAAAAAAAQIDBAUGBwj/xAA+EQEBAAICAQMBBgMFBQYHAAAAAQIRITEDBBJBBQYiMlFhcROBoQcVQrHRUpGywfAXJCUzktI0NmJygqLh/9oADAMB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resident_Evil_4_Remake___Image {
            get {
                return ResourceManager.GetString("Resident Evil 4 Remake - Image", resourceCulture);
            }
        }
    }
}
